### ISSUE TITLE
MERCIER DEVICES WITHOUT POWER

### ISSUE THREAD

**Issue by JulienVividi** [iterait/vividi-pharmaflix#8]
Hi, all devices in MERCIER are without POWER can you check please ? 
Thank you
![MERCIER](https://user-images.githubusercontent.com/115627901/201950366-a4dd7c5b-473e-4208-8aae-dd687fc0e564.png)

**Comment by pharmaflix** [comment]
Laurent, please check and revert. Best




 [cid:f8e4acb9-bbbd-440a-b923-0cc9530e618a] <https://www.pharmaflix.fr/>

Guillaume-Henri HUREL | Expert Innovation Retail Media

PHARMAFLIX

21 Place de la République 75003 Paris

+33 6 34 38 11 59

www.pharmaflix.fr<http://www.pharmaflix.fr/>

________________________________
De : JulienVividi ***@***.***>
Envoyé : mardi 15 novembre 2022 15:53
À : iterait/vividi-pharmaflix ***@***.***>
Cc : Guillaume-Henri Hurel ***@***.***>; Assign ***@***.***>
Objet : [iterait/vividi-pharmaflix] MERCIER DEVICES WITHOUT POWER (Issue #8)


Hi, all devices in MERCIER are without POWER can you check please ?
Thank you
[MERCIER]<https://user-images.githubusercontent.com/115627901/201950366-a4dd7c5b-473e-4208-8aae-dd687fc0e564.png>

**Comment by pharmaflix** [comment]
@JulienVividi just learned that devices have been removed due to heavy work in progress in the pharma. will be reinstalled later on. keep in touch but this pharmacy is in STAND BY now. Best

**Comment by JulienVividi** [comment]
Ok, received thank you!
